openapi: 3.0.0
info:
  title: BKK Transit API
  version: 1.0.0
paths:
  /api/stations:
    get:
      summary: ดึงข้อมูลสถานีทั้งหมด
      responses:
        '200':
          description: สำเร็จ
          content:
            application/json:    
              schema:
                $ref: '#/components/schemas/StationList'
        '404':
          $ref: '#/components/responses/NotFound'
  
  /api/stations/{stationId}:
    get:
      summary: ดึงข้อมูลสถานีเฉพาะ
      parameters:
        - in: path
          name: stationId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: สำเร็จ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StationDetail'
        '404':
          $ref: '#/components/responses/NotFound'
  
  /api/routes/search:
    post:
      summary: ค้นหาเส้นทาง
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RouteSearchRequest'
      responses:
        '201':
          description: สำเร็จ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Route'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/lines:
    get:
      summary: ดึงข้อมูลสายรถไฟฟ้าทั้งหมด
      responses:
        '200':
          description: สำเร็จ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LineList'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/fares:
    get:
      summary: ดึงข้อมูลค่าโดยสาร
      parameters:
        - in: query
          name: from
          required: true
          schema:
            type: string
        - in: query
          name: to
          required: true
          schema:
            type: string
      responses:
        '200':
          description: สำเร็จ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fare'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/schedules:
    get:
      summary: ดึงข้อมูลเวลาเดินรถ
      parameters:
        - in: query
          name: stationId
          required: true
          schema:
            type: string
        - in: query
          name: direction
          required: true
          schema:
            type: string
            enum: [inbound, outbound]
      responses:
        '200':
          description: สำเร็จ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schedule'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/reports:
    post:
      summary: รายงานปัญหาหรือเหตุขัดข้อง
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReportRequest'
      responses:
        '201':
          description: สำเร็จ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportResponse'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  schemas:
    Station:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        line:
          type: string
    
    StationList:
      type: object
      properties:
        status:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/Station'
    
    StationDetail:
      type: object
      properties:
        status:
          type: string
        data:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            line:
              type: string
            connections:
              type: array
              items:
                type: string
            facilities:
              type: array
              items:
                type: string
            nearbyPlaces:
              type: array
              items:
                type: string
    
    RouteSearchRequest:
      type: object
      properties:
        startStationId:
          type: string
        endStationId:
          type: string
    
    Route:
      type: object
      properties:
        status:
          type: string
        data:
          type: object
          properties:
            start:
              $ref: '#/components/schemas/Station'
            end:
              $ref: '#/components/schemas/Station'
            stations:
              type: array
              items:
                $ref: '#/components/schemas/Station'
            totalStations:
              type: integer
            lines:
              type: array
              items:
                type: string
            estimatedTime:
              type: integer
            hasTransfer:
              type: boolean

    LineList:
      type: object
      properties:
        status:
          type: string
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              name:
                type: string
              color:
                type: string

    Fare:
      type: object
      properties:
        status:
          type: string
        data:
          type: object
          properties:
            fare:
              type: number
            currency:
              type: string

    Schedule:
      type: object
      properties:
        status:
          type: string
        data:
          type: object
          properties:
            stationId:
              type: string
            stationName:
              type: string
            direction:
              type: string
            schedules:
              type: array
              items:
                type: object
                properties:
                  time:
                    type: string
                  destination:
                    type: string

    ReportRequest:
      type: object
      properties:
        stationId:
          type: string
        type:
          type: string
        description:
          type: string
        reportedBy:
          type: string

    ReportResponse:
      type: object
      properties:
        status:
          type: string
        data:
          type: object
          properties:
            reportId:
              type: string
            message:
              type: string
  
  responses:
    NotFound:
      description: ไม่พบข้อมูล
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
              message:
                type: string
              errorCode:
                type: string